1. Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array.
Expected Output:
Original List: [12.23, 13.32, 100, 36.32]
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]

In [32]:
import numpy as np
num_lst = [12.23,13.32,100,36.32]
np_arr = np.array(num_lst)
print("Original:",num_lst)
print("One-D array:",np_arr)


Original: [12.23, 13.32, 100, 36.32]
One-D array: [ 12.23  13.32 100.    36.32]


2. Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]


In [33]:
import numpy as np
matrix = np.arange(2,11).reshape(3,3)
print(matrix)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3. Write a Python program to create a null vector of size 10 and update sixth value to 11.
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]


In [34]:
import numpy as np
vector = np.zeros(10)
print("Original Vector:")
print(vector)
vector[6] = 11
print("Updated Vector:")
print(vector)

Original Vector:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Updated Vector:
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


4. Write a Python program to reverse an array (first element becomes last).
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [35]:
import numpy as np
arr = np.arange(12,38)
print("Original array:")
print(arr)
reversed_arr = arr[::-1]
print("Reversed array:")
print(reversed_arr)

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reversed array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


5. Write a Python program to create a 2d array with 1 on the border and 0 inside.
Expected Output:
Original array:
[[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 1. 1. 1. 1.]]


In [36]:
import numpy as np
size = 5
array = np.ones((size,size))
print("Original array:")
print(array)
array[1:-1,1:-1] = 0
print("Updated array:")
print(array)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Updated array:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


6. Write a Python program to add a border (filled with 0's) around an existing array.
Expected Output:
Original array:
[[ 1. 1. 1.]
[ 1. 1. 1.]
[ 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 0. 0. 0. 0. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 0. 0. 0. 0.]]


In [37]:
import numpy as np
original_array = np.ones((3,3))
print("Original Array:")
print(original_array)
bordered_array = np.pad(original_array,pad_width = 1,mode='constant',constant_values=0)
print("\nArray with bordering:")
print(bordered_array)

Original Array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array with bordering:
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]

In [38]:
import numpy as np
checkboard = np.zeros((8,8),dtype=int)
checkboard[::2,1::2] = 1
checkboard[1::2,::2] = 1
print("Checkboard pattern:")
print(checkboard)

Checkboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


8. Write a Python program to convert a list and tuple into arrays.
List to array:
[1 2 3 4 5 6 7 8]
Tuple to array:
[[8 4 6]
[1 2 3]]

In [39]:
import numpy as np
num_lst = [1,2,3,4,5,6,7,8]
num_tuple = ((8,4,6),(1,2,3))
array_lst = np.array(num_lst)
array_tuple = np.array(num_tuple)
print("List to array:")
print(array_lst)
print("Tuples to array:")
print(array_tuple)

List to array:
[1 2 3 4 5 6 7 8]
Tuples to array:
[[8 4 6]
 [1 2 3]]


9. Write a Python program to append values to the end of an array.
Expected Output:
Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]


In [40]:
import numpy as np
orignal_array = np.array([10,20,30])
print("Original array:")
print(orignal_array)
values_to_append = [40,50,60,70,80,90,100]
updated_array = np.append(orignal_array,values_to_append)
print("After appending values:")
print(updated_array)

Original array:
[10 20 30]
After appending values:
[ 10  20  30  40  50  60  70  80  90 100]


10. Write a Python program to find the real and imaginary parts of an array of complex
numbers.
Expected Output:
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]
Real part of the array:
[ 1. 0.70710678]
Imaginary part of the array:
[ 0. 0.70710678]


In [41]:
import numpy as np
complex_array = np.array([1+2j,3+4j])
print("Original array:")
print(complex_array)
real_part = np.real(complex_array)
imaginary_part = np.imag(complex_array)
print("Real part of the array:")
print(real_part)
print("Imaginary part of the array:")
print(imaginary_part)

Original array:
[1.+2.j 3.+4.j]
Real part of the array:
[1. 3.]
Imaginary part of the array:
[2. 4.]


11. Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements.
Expected Output:
Size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24


In [42]:
import numpy as np
arr = np.array([0,10,20,40,60],dtype=np.int64)
size = arr.size
element_size = arr.itemsize
total_bytes = arr.nbytes
print("Size of the array:",size)
print("Length of an array element in bytes:",element_size)
print("Total bytes consumedby the elements of the array:",total_bytes)

Size of the array: 5
Length of an array element in bytes: 8
Total bytes consumedby the elements of the array: 40


12. Write a Python program to find common values between two arrays.
Expected Output:
Array1: [ 0 10 20 40 60]
Array2: [10, 30, 40]
Common values between two arrays:
[10 40]

In [43]:
import numpy as np
array1 = np.array([0,10,20,40,60])
array2 = np. array([10,30,40])
print("Array1:",array1)
print("array2:",array2)
common_values = np.intersect1d(array1,array2)
print("Common values betwenn two arrays")
print(common_values)

Array1: [ 0 10 20 40 60]
array2: [10 30 40]
Common values betwenn two arrays
[10 40]


13. Write a Python program to find the set difference of two arrays. The set difference
will return the sorted, unique values in array1 that are not in array2.
Expected Output:
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70, 90]
Set difference between two arrays:
[ 0 20 60 80]

In [44]:
import numpy as np
array1 = np.array([0,10,20,40,60,80])
array2 = np.array([10,30,40,50,70,90])
print("Array1:",array1)
print("Array2:",array2)
set_diff = np.setdiff1d(array1,array2)
print(set_diff)

Array1: [ 0 10 20 40 60 80]
Array2: [10 30 40 50 70 90]
[ 0 20 60 80]


14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or
will return the sorted, unique values that are in only one (not both) of the input arrays.
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]

In [45]:
import numpy as np
array1 = np.array([0,10,20,40,60,80])
array2 = np.array([10,30,40,50,70])
print("Array1:",array1)
print("Array2:",array2)
exclusive_or = np.setxor1d(array1,array2)
print("Unique values that are in only one of the input arrays")
print(exclusive_or)

Array1: [ 0 10 20 40 60 80]
Array2: [10 30 40 50 70]
Unique values that are in only one of the input arrays
[ 0 20 30 50 60 70 80]


15. Write a Python program compare two arrays using numpy.
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]

In [46]:
import numpy as np

a = np.array([10,20])
b = np.array([40,50])
print("Array a:",a)
print("Array b:",b)
print("\na>b")
print(a>b)
print("\na<b")
print(a<b)
print("\na>=b")
print(a>=b)
print("\na<=b")
print(a<=b)



Array a: [10 20]
Array b: [40 50]

a>b
[False False]

a<b
[ True  True]

a>=b
[False False]

a<=b
[ True  True]


15. Write a Python program to save a NumPy array to a text file.


In [47]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.savetxt("array.txt",arr,fmt="%d")
print("Numpy array has been saved to array.txt")


Numpy array has been saved to array.txt


16. Write a Python program to create a contiguous flattened array.
Original array:
[[10 20 30]
[20 40 50]]
New flattened array:
[10 20 30 20 40 50]


In [48]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Original array:")
print(arr)
flattened_arr = arr.flatten()
print("\nFlattened array:")
print(flattened_arr)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flattened array:
[1 2 3 4 5 6 7 8 9]


17. Write a Python program to change the data type of an array.
Expected Output:
[[ 2 4 6]
[ 6 8 10]]
Data type of the array x is: int32
New Type: float64
[[ 2. 4. 6.]
[ 6. 8. 10.]]

In [49]:
import numpy as np
x = np.array([[2,4,6],[6,8,10]])
print("Original array:")
print(x)
print("\nData type of the array x is:",x.dtype)
x_float = x.astype(np.float64)
print("New array:",x_float)
print("Data type of the new array x_float is:",x_float.dtype)


Original array:
[[ 2  4  6]
 [ 6  8 10]]

Data type of the array x is: int32
New array: [[ 2.  4.  6.]
 [ 6.  8. 10.]]
Data type of the new array x_float is: float64


18. Write a Python program to create a 3-D array with ones on a diagonal and zeros
elsewhere.
Expected Output:
[[ 1. 0. 0.]
[ 0. 1. 0.]
[ 0. 0. 1.]]

In [50]:
import numpy as np
array_3d = np.eye(3)
print("3-D array with ones on the diagonal and zeros elsewhere:")
print(array_3d)

3-D array with ones on the diagonal and zeros elsewhere:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


19. Write a Python program to create an array which looks like below array.
Expected Output:
[[ 0. 0. 0.]
[ 1. 0. 0.]
[ 1. 1. 0.]
[ 1. 1. 1.]]

In [51]:
import numpy as np
array = np.tri(4,3,-1,dtype=float)
print("Generated array:")
print(array)

Generated array:
[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


20. Write a Python program to concatenate two 2-dimensional arrays.
Expected Output:
Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]])
Expected Output:
[[ 0 1 3 0 2 4]
[ 5 7 9 6 8 10]]

In [52]:
import numpy as np
array1 = np.array([[0,1,3],[5,7,9]])
array2 = np.array([[0,2,4],[6,8,10]])
result = np.concatenate((array1,array2),axis=1)
print("Concatenated array:")
print(result)

Concatenated array:
[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


21. Write a Python program to make an array immutable (read-only).
Expected Output:
Test the array is read-only or not:
Try to change the value of the first element:
Traceback (most recent call last):
File "19236bd0-0bd9-11e7-a232-c706d0968eb6.py", line 6, in
x[0] = 1
ValueError: assignment destination is read-only

In [53]:
import numpy as np
x = np.array([10,20,30,40,50])
x.flags.writeable = False
print("Test the array is read only or not")
try:
    x[0] = 80
except ValueError as e:
    print("Error:",e)

Test the array is read only or not
Error: assignment destination is read-only


22. Write a Python program to create an array of (3, 4) shape, multiply every element
value by 3 and display the new array.
Expected Output:
Original array elements:
[[ 0 1 2 3]
[ 4 5 6 7]
[ 8 9 10 11]]
New array elements:
[[ 0 3 6 9]
[12 15 18 21]
[24 27 30 33]]

In [54]:
import numpy as np
array = np.arange(12).reshape(3,4)
print("Original array:")
print(array)
new_array = array*3
print("New array:")
print(new_array)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
New array:
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


23. Write a Python program to convert a NumPy array into Python list structure.
Expected Output:
Original array elements:
[[0 1]
[2 3]
[4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]

In [55]:
import numpy as np
array = np.array([[0,1],[2,3],[4,5]])
print("Original array:")
print(array)
array_to_list = array.tolist()
print("Array to list:")
print(array_to_list)

Original array:
[[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


24. Write a Python program to convert a NumPy array into Python list structure.
Expected Output:
Original array elements:
[ 0.26153123 0.52760141 0.5718299 0.5927067 0.7831874 0.69746349
0.35399976 0.99469633 0.0694458 0.54711478]
Print array values with precision 3:
[ 0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]

In [57]:
import numpy as np
array = np.random.rand(10)
print("Original array:")
print(repr(array))
array_to_list = array.tolist()
rounded_array = np.round(array,2)
print("Rounded array:")
print(rounded_array)

Original array:
array([0.444, 0.105, 0.341, 0.177, 0.365, 0.744, 0.087, 0.716, 0.662,
       0.112])
Rounded array:
[0.44 0.1  0.34 0.18 0.36 0.74 0.09 0.72 0.66 0.11]


In [58]:
import numpy as np
array = np.array([1.6e-10,1.6,1.2e3,2.35e-1])
print("Original array:")
print(array)
np.set_printoptions(suppress=True,precision=3)
print("Print array values with precision 3:")
print(array)

Original array:
[1.60e-10 1.60e+00 1.20e+03 2.35e-01]
Print array values with precision 3:
[   0.       1.6   1200.       0.235]


26. Write a Python program to how to add an extra column to an numpy array.
Expected Output:
[[ 10 20 30 100]
[ 40 50 60 200]]


In [59]:
import numpy as np
array = np.array([[10,20,30],[40,50,60]])
new_col = np.array([[100],[200]])
print("Original array:")
print(array)
result = np.column_stack((array,new_col))
print("New column stack:")
print(result)

Original array:
[[10 20 30]
 [40 50 60]]
New column stack:
[[ 10  20  30 100]
 [ 40  50  60 200]]


27. Write a Python program to remove specific elements in a numpy array.
Expected Output:
Original array:
[ 10 20 30 40 50 60 70 80 90 100]
Delete first, fourth and fifth elements:
[ 20 30 60 70 80 90 100]


In [60]:
import numpy as np
array = np.arange(10,100,10)
print("Original Array:")
print(array)
indexes = [0,4,6]
result = np.delete(array,indexes)
print("After removing the indexes:")
print(result)

Original Array:
[10 20 30 40 50 60 70 80 90]
After removing the indexes:
[20 30 40 60 80 90]
